# Generated by Django 2.0.3 on 2018-07-23 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_comment'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author_id',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
