# Generated by Django 2.0.3 on 2018-07-25 10:27

import blog.models
import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_comment_author_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.ImageField(blank=True, null=True, storage=django.core.files.storage.FileSystemStorage(base_url='/media/images/', location='/home/wsc-194a/workspace/OpenGameArt/opengameart/media/images/'), upload_to=blog.models.image_directory_path),
        ),
    ]
