# Generated by Django 2.0.3 on 2018-06-14 07:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Art',
            fields=[
                ('id', models.CharField(max_length=100, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('file_path', models.CharField(max_length=255)),
                ('file', models.ImageField(upload_to='')),
                ('creation_date', models.DateTimeField(default=datetime.date.today)),
                ('likes', models.IntegerField(default=0)),
            ],
        ),
    ]
