# Generated by Django 2.0.3 on 2018-06-14 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
