# Generated by Django 2.0.3 on 2018-07-10 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_auto_20180710_0911'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='owner_id',
            field=models.CharField(default='', max_length=255),
        ),
    ]
