# Generated by Django 2.0.3 on 2018-06-14 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0002_auto_20180614_0739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='file',
            field=models.ImageField(blank=True, null=True, upload_to='images/loaded/'),
        ),
    ]
