# Generated by Django 2.0.3 on 2018-07-25 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('country', models.CharField(max_length=255)),
                ('subject_text', models.TextField()),
            ],
        ),
    ]
