# Generated by Django 2.0.3 on 2018-07-11 08:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('arts', '0003_art_owner_id'),
        ('accounts', '0002_artuser_user_avatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('art', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='arts.Art')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.ArtUser')),
            ],
        ),
    ]
