# Generated by Django 2.0.3 on 2018-07-19 10:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_artuser_liked_arts'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relationship',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.IntegerField(choices=[(1, 'Following'), (2, 'Blocked')])),
                ('from_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='from_people', to='accounts.ArtUser')),
                ('to_person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='to_people', to='accounts.ArtUser')),
            ],
        ),
        migrations.AddField(
            model_name='artuser',
            name='relationships',
            field=models.ManyToManyField(related_name='related_to', through='accounts.Relationship', to='accounts.ArtUser'),
        ),
    ]
